// netlify/functions/paipo-api.js
const { createClient } = require('@supabase/supabase-js');
const { Octokit } = require('@octokit/rest');

// Environment variables (set in Netlify)
const SUPABASE_URL = process.env.SUPABASE_URL;
const SUPABASE_SERVICE_KEY = process.env.SUPABASE_SERVICE_KEY; // use service key for full access
const GITHUB_TOKEN = process.env.GITHUB_TOKEN;
const GITHUB_OWNER = process.env.GITHUB_OWNER;
const GITHUB_REPO = process.env.GITHUB_REPO;
const GITHUB_BRANCH = process.env.GITHUB_BRANCH || 'main';

const supabase = createClient(SUPABASE_URL, SUPABASE_SERVICE_KEY);
const octokit = new Octokit({ auth: GITHUB_TOKEN });

exports.handler = async (event) => {
  // Only allow POST
  if (event.httpMethod !== 'POST') {
    return { statusCode: 405, body: JSON.stringify({ error: 'Method not allowed' }) };
  }

  let payload;
  try {
    payload = JSON.parse(event.body);
  } catch (e) {
    return { statusCode: 400, body: JSON.stringify({ error: 'Invalid JSON' }) };
  }

  const { action } = payload;

  try {
    let result;
    switch (action) {
      case 'ensureUser':
        result = await handleEnsureUser(payload);
        break;
      case 'getPosts':
        result = await handleGetPosts();
        break;
      case 'createPost':
        result = await handleCreatePost(payload);
        break;
      case 'getPostFiles':
        result = await handleGetPostFiles(payload);
        break;
      case 'pushFiles':
        result = await handlePushFiles(payload);
        break;
      case 'likePost':
        result = await handleLikePost(payload);
        break;
      case 'unlikePost':
        result = await handleUnlikePost(payload);
        break;
      case 'getLikes':
        result = await handleGetLikes(payload);
        break;
      case 'addComment':
        result = await handleAddComment(payload);
        break;
      case 'getComments':
        result = await handleGetComments(payload);
        break;
      case 'forkPost':
        result = await handleForkPost(payload);
        break;
      default:
        return { statusCode: 400, body: JSON.stringify({ error: 'Unknown action' }) };
    }

    return {
      statusCode: 200,
      headers: { 'Access-Control-Allow-Origin': '*' },
      body: JSON.stringify(result)
    };
  } catch (error) {
    console.error('Function error:', error);
    return {
      statusCode: 500,
      body: JSON.stringify({ error: error.message })
    };
  }
};

// ----------------- Handlers -----------------

async function handleEnsureUser({ anonymousId, displayName }) {
  // Check if user exists, if not insert
  const { data, error } = await supabase
    .from('PAIPo_AutoGenerated')
    .select('*')
    .eq('anonymous_id', anonymousId)
    .maybeSingle();

  if (error) throw error;
  if (!data) {
    const { data: newUser, error: insertError } = await supabase
      .from('PAIPo_AutoGenerated')
      .insert({ anonymous_id: anonymousId, display_name: displayName })
      .select()
      .single();
    if (insertError) throw insertError;
    return { user: newUser };
  }
  return { user: data };
}

async function handleGetPosts() {
  const { data, error } = await supabase
    .from('PAIPo_Posts')
    .select(`
      *,
      likes:PAIPo_Likes(count),
      comments:PAIPo_Comments(count),
      forks:PAIPo_Fork!original_post_id(count)
    `)
    .order('created_at', { ascending: false });
  if (error) throw error;
  // Format counts
  const posts = data.map(p => ({
    ...p,
    likes_count: p.likes?.[0]?.count || 0,
    comments_count: p.comments?.[0]?.count || 0,
    forks_count: p.forks?.[0]?.count || 0
  }));
  return { posts };
}

async function handleCreatePost({ anonymousId, title, description, repoPath }) {
  // Generate a unique repo path (e.g., using UUID or slug)
  const postId = crypto.randomUUID();
  const path = repoPath || `posts/${postId}`;
  const { data, error } = await supabase
    .from('PAIPo_Posts')
    .insert({
      id: postId,
      anonymous_id: anonymousId,
      title,
      description: description || '',
      repo_path: path
    })
    .select()
    .single();
  if (error) throw error;
  return { post: data };
}

async function handleGetPostFiles({ postId }) {
  // Fetch from GitHub: get contents of the folder corresponding to post.repo_path
  const { data: post, error: postError } = await supabase
    .from('PAIPo_Posts')
    .select('repo_path')
    .eq('id', postId)
    .single();
  if (postError) throw postError;
  if (!post) throw new Error('Post not found');

  // Get contents from GitHub
  try {
    const { data: contents } = await octokit.repos.getContent({
      owner: GITHUB_OWNER,
      repo: GITHUB_REPO,
      path: post.repo_path,
      ref: GITHUB_BRANCH
    });

    // If it's a directory, recursively fetch files (simplified: only top-level for now)
    // For simplicity, we'll assume we store files as a flat list in the database? Or we fetch each file.
    // Better: store file list in a manifest or fetch recursively. We'll implement a simple version:
    const files = [];
    if (Array.isArray(contents)) {
      // directory
      for (const item of contents) {
        if (item.type === 'file') {
          const { data: fileContent } = await octokit.repos.getContent({
            owner: GITHUB_OWNER,
            repo: GITHUB_REPO,
            path: item.path,
            ref: GITHUB_BRANCH
          });
          files.push({
            path: item.path.replace(post.repo_path + '/', ''),
            content: Buffer.from(fileContent.content, 'base64').toString()
          });
        }
      }
    } else if (contents.type === 'file') {
      // single file? unlikely
      files.push({
        path: contents.path.replace(post.repo_path + '/', ''),
        content: Buffer.from(contents.content, 'base64').toString()
      });
    }
    return { files };
  } catch (e) {
    // If repo path doesn't exist, return empty
    return { files: [] };
  }
}

async function handlePushFiles({ postId, files }) {
  // files: array of { path, content }
  const { data: post, error: postError } = await supabase
    .from('PAIPo_Posts')
    .select('repo_path')
    .eq('id', postId)
    .single();
  if (postError) throw postError;

  const repoPath = post.repo_path;

  // Get current head commit
  const { data: refData } = await octokit.git.getRef({
    owner: GITHUB_OWNER,
    repo: GITHUB_REPO,
    ref: `heads/${GITHUB_BRANCH}`
  });
  const latestCommitSha = refData.object.sha;

  const { data: commitData } = await octokit.git.getCommit({
    owner: GITHUB_OWNER,
    repo: GITHUB_REPO,
    commit_sha: latestCommitSha
  });
  const baseTreeSha = commitData.tree.sha;

  // Create blobs for each file
  const treeItems = await Promise.all(files.map(async (file) => {
    const fullPath = `${repoPath}/${file.path}`;
    const { data: blob } = await octokit.git.createBlob({
      owner: GITHUB_OWNER,
      repo: GITHUB_REPO,
      content: Buffer.from(file.content).toString('base64'),
      encoding: 'base64'
    });
    return {
      path: fullPath,
      mode: '100644',
      type: 'blob',
      sha: blob.sha
    };
  }));

  // Create new tree
  const { data: newTree } = await octokit.git.createTree({
    owner: GITHUB_OWNER,
    repo: GITHUB_REPO,
    base_tree: baseTreeSha,
    tree: treeItems
  });

  // Create commit
  const { data: newCommit } = await octokit.git.createCommit({
    owner: GITHUB_OWNER,
    repo: GITHUB_REPO,
    message: `Update files for post ${postId}`,
    tree: newTree.sha,
    parents: [latestCommitSha]
  });

  // Update branch
  await octokit.git.updateRef({
    owner: GITHUB_OWNER,
    repo: GITHUB_REPO,
    ref: `heads/${GITHUB_BRANCH}`,
    sha: newCommit.sha,
    force: false
  });

  return { success: true };
}

async function handleLikePost({ postId, anonymousId }) {
  const { error } = await supabase
    .from('PAIPo_Likes')
    .insert({ post_id: postId, anonymous_id: anonymousId });
  if (error) throw error;
  return { success: true };
}

async function handleUnlikePost({ postId, anonymousId }) {
  const { error } = await supabase
    .from('PAIPo_Likes')
    .delete()
    .eq('post_id', postId)
    .eq('anonymous_id', anonymousId);
  if (error) throw error;
  return { success: true };
}

async function handleGetLikes({ postId }) {
  const { data, error, count } = await supabase
    .from('PAIPo_Likes')
    .select('*', { count: 'exact' })
    .eq('post_id', postId);
  if (error) throw error;
  return { likes: data, count };
}

async function handleAddComment({ postId, anonymousId, content, parentCommentId }) {
  const { data, error } = await supabase
    .from('PAIPo_Comments')
    .insert({
      post_id: postId,
      anonymous_id: anonymousId,
      content,
      parent_comment_id: parentCommentId || null
    })
    .select()
    .single();
  if (error) throw error;
  return { comment: data };
}

async function handleGetComments({ postId }) {
  const { data, error } = await supabase
    .from('PAIPo_Comments')
    .select(`
      *,
      user:PAIPo_AutoGenerated(display_name)
    `)
    .eq('post_id', postId)
    .order('created_at', { ascending: true });
  if (error) throw error;
  return { comments: data };
}

async function handleForkPost({ originalPostId, anonymousId, newTitle }) {
  // Get original post
  const { data: original, error: origError } = await supabase
    .from('PAIPo_Posts')
    .select('*')
    .eq('id', originalPostId)
    .single();
  if (origError) throw origError;

  // Create new post
  const newPostId = crypto.randomUUID();
  const newRepoPath = `posts/${newPostId}`;

  const { data: newPost, error: createError } = await supabase
    .from('PAIPo_Posts')
    .insert({
      id: newPostId,
      anonymous_id: anonymousId,
      title: newTitle || original.title + ' (fork)',
      description: original.description,
      repo_path: newRepoPath,
      forked_from: originalPostId
    })
    .select()
    .single();
  if (createError) throw createError;

  // Record fork
  await supabase.from('PAIPo_Fork').insert({
    original_post_id: originalPostId,
    forked_post_id: newPostId,
    anonymous_id: anonymousId
  });

  // Copy files from original repo to new repo path
  // We need to copy the entire folder from original.repo_path to newRepoPath
  // For simplicity, we'll do a recursive copy using GitHub API
  try {
    const { data: contents } = await octokit.repos.getContent({
      owner: GITHUB_OWNER,
      repo: GITHUB_REPO,
      path: original.repo_path,
      ref: GITHUB_BRANCH
    });

    // We'll need to create the same folder structure. We'll collect all files.
    const filesToCopy = [];
    if (Array.isArray(contents)) {
      for (const item of contents) {
        if (item.type === 'file') {
          const { data: fileData } = await octokit.repos.getContent({
            owner: GITHUB_OWNER,
            repo: GITHUB_REPO,
            path: item.path,
            ref: GITHUB_BRANCH
          });
          filesToCopy.push({
            path: item.path.replace(original.repo_path, newRepoPath),
            content: Buffer.from(fileData.content, 'base64').toString()
          });
        }
        // ignore subfolders for simplicity, but could recurse
      }
    } else if (contents.type === 'file') {
      filesToCopy.push({
        path: contents.path.replace(original.repo_path, newRepoPath),
        content: Buffer.from(contents.content, 'base64').toString()
      });
    }

    // Now push these files using handlePushFiles but with new post ID
    await handlePushFiles({ postId: newPostId, files: filesToCopy });
  } catch (e) {
    // If no files, just continue
    console.warn('Could not copy files for fork:', e);
  }

  return { post: newPost };
}
